### ISSUE TITLE
[Suggestion] Add cookbook_path source

### ISSUE THREAD

**Issue by zhelyan** [spox/batali#78]
So we use a monolithic chef-repo and I want to save myself the trouble of adding a CB to the Batali file every time one is created. I tried:

```ruby
def company_cookbook(name, version = '>= 0.0.0', options = {})
  cookbook(name, version, {
    path: "../#{name}"
   }.merge(options))
end

Batali.define do
  source 'https://supermarket.chef.io'

 %w(cookbook1 cookbook2 ....).each{|name| company_cookbook(name) }
end
```

which failed with `[ERROR]: Reason - Failed to load configuration from file (/Users/zpanche/chef/chef-repo/Batali)`

Is it worth adding a new source , e.g. `cookbook_path` which defaults to the `cookbook_path` in the Chef config, then:

```
Batali.define do
  source 'https://supermarket.chef.io'
  source cookbook_path: [ 'site-cookbooks', 'cookbooks' ] # or default to paths from i.e. knife.rb
  discover true
end
``` 
Which would make `batali resolve --infrastructure` also look in `cookbook_path` for cookbooks required in roles, envs etc.; These should have precedence over cookbooks with same name from other sources.

**Comment by chrisroberts** [comment]
I would warn against using `cookbooks` as a directory to store tracked cookbooks as this is the default location `batali install` will install to. For automatically loading cookbooks in a directory you can easily just loop the directory contents:

```ruby
Batali.define do
  source 'https://supermarket.chef.io'
  Dir.new('./site-cookbooks').each do |ckbk|
    if(File.exists?(File.join('./site-cookbooks', ckbk, 'metadata.rb')))
      cookbook ckbk, :path => File.join('./site-cookbooks', ckbk)
    end
  end
end
```

This assumes your cookbook directory is the same name as your cookbook and that you use Ruby metadata files and not JSON. However, it should be enough to get started with and adjust to your needs. 

I will mull over the `cookbook_path` attribute but I'm generally against features like this because there are too many possibilities for "expected behavior". However, if I can come up with an acceptable "standard" that is required for it to function, I'll be open to adding it.

Thanks!

**Comment by zhelyan** [comment]
Excellent, thanks! How does this work when used together with `chef_server`? Or, more generally, are sources searched in the order they are declared?

**Comment by chrisroberts** [comment]
I'm going to pass on adding the `cookbook_path
